### ISSUE TITLE
Can not log in

### ISSUE THREAD

**Issue by JohnMisk1** [FatherFoxxy/SteamToolkit#1]
Hey. what could be the problem? Can not be authorized. Login and password are correct, but from the Steam comes such an answer:
`"{\"success\":false,\"requires_twofactor\":false,\"clear_password_field\":true,\"captcha_needed\":false,\"captcha_gid\":-1,\"message\":\"Incorrect login.\"}"`

**Comment by ChernayaKoshka** [comment]
Yup. Steam updated their login system to prevent bots. Unfortunately, I am not experienced enough with web stuff to bypass it. However, I did build another way to log in which I will link after I get off work.

**Comment by JohnMisk1** [comment]
I started using cookies in all queries and taking the password calculation code from  [SteamAuth](https://github.com/geel9/SteamAuth/blob/master/SteamAuth/UserLogin.cs#L71) I was able to log in

**Comment by ChernayaKoshka** [comment]
Submit a pull request adding a new login method please :)

**Comment by ChernayaKoshka** [comment]
Wait a sec, I'm confused though. Because mine should be identical to that iirc

**Comment by JohnMisk1** [comment]
This code does not look nice, but it works, probably :) [Web.cs](https://gist.github.com/JohnMisk1/ea4cfae88e60e484d499c0b86bb77577)

**Comment by ChernayaKoshka** [comment]
Fixed main login in commit https://github.com/FatherFoxxy/SteamToolkit/commit/fc35114b8de5a87f8ad98669b7fb57b1ea0040b6 thanks to @millworm
